print("CHECKING THE TYPE OF DATATYPE OF THE GIVEN VARIABLE :")
a=input("enter the name: ")
b=int(input('ENTER THE VALUE :'))
c=float(input('ENTER the decimeal value'))
d=bool(input("ENTER TRUE OR FALSE :"))
print(type(a))
print(type(b))
print(type(c))
print(type(d))